### ISSUE TITLE
Feature request: ability to add custom configs for each branch

### ISSUE THREAD

**Issue by shawnbot** [18F/federalist#116]
The custom configurations in #112 are awesome! What would be *even more* awesome would be the ability to configure custom configurations for each branch individually. This would be allow us to keep API keys for one of our projects out of the source (but, admittedly, in the rendered HTML or JS) and keep our `dev` and `staging` workflow branches in sync with the corresponding API environments.

**Comment by dhcole** [comment]
What if we exposed the branch as a `site.branch` attribute, so you could do something like this in your config:

```yml
api:
  master: UDNQK2SB0G
  staging: 8PKO3343AV
```

and you would access it like `{{ site.api[site.branch] }}`

Would that work?

Alternatively, you could set up branch-specific configuration in blocks:

```yml

master:
  api: UDNQK2SB0G
  foo: ...
  bar: ...
staging:
  api: 8PKO3343AV
  foo: ...
  bar: ...
```

and access it a similar way `{{ site[site.branch].api }}`
