### ISSUE TITLE
Extend metadata fields with custom values

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#293]
While developing a static site with a defined list of options for some metadata fields, having custom metadata fields would be really helpful. For instance, to populate content with a `topic` dropdown field, we could define something like this in `_config.yml`

``` yml
defaults:
  -
    scope:
      path: ""
      type: people
    values:
      layout:
        - default
        - page
      topic:
        type: select
        options:
          - open-source
          - development
          - design
```

Layout is included as an example of how this already works for a whitelisted field; however, layout has a slightly different syntax, forgoing the `type` attribute.

It would also be useful to have `checkbox` and `radio` types in addition to `select`, but that could be a separate task.
