### ISSUE TITLE
Jekyll build fails to append custom _config.yml?

### ISSUE THREAD

**Issue by shawnbot** [18F/federalist#436]
The branch preview for [this pull request](https://github.com/18F/college-choice/pull/1532) failed to build, and [the log](https://federalist.18f.gov/#site/3/logs) says:

```
jekyll 2.4.0 | Error: (./_config.yml): did not find expected ',' or '}'
while parsing a flow mapping at line 58 column 9
```

The [_config.yml](https://github.com/18F/college-choice/blob/add-default-zip-distance/_config.yml) is 56 lines long, and the custom config looks like this, with email addresses and API keys masked:

```
API:
  # by default, use the dev API
  baseurl: https://api.data.gov/TEST/ed/dev/v1/
  key: XXXX

  # use the public-facing production API on the master branch
  # this is <XXXX>'s API key
  master:
    baseurl: https://api.data.gov/ed/collegescorecard/v1/
    key: XXXX
    newrelic: 8349766

  dev:
    baseurl: https://api.data.gov/TEST/ed/dev/v1/
    key: XXXX
    newrelic: 7635520

  staging:
    baseurl: https://api.data.gov/TEST/ed/staging/v1/
    key: XXXX
    newrelic: 7790612

  ex:
    baseurl: https://api.data.gov/TEST/ed/ex/v1/
    key: XXXX
```

I don't know how the custom config gets appended, but if it's just being concatenated then maybe there's something happening in that process that's generating invalid YAML? I really don't know, and I'm 100% unsure how to debug this any further.

cc @kynetiv for visibility
