### ISSUE TITLE
Setup Clair

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#541]
# What we know about Clair:

[Clair](https://github.com/coreos/clair) is an open source project that enables vulnerability scanning of Docker images.

Clair can be configured to [scan local Docker images](https://github.com/coreos/clair/tree/master/contrib/analyze-local-images). Additionally, Clair can be configured to [run in a Docker container](https://github.com/coreos/clair#docker) and [connect with a Docker registry](https://github.com/coreos/clair#container-registry-integration) to provide continuous scanning when Docker images are pushed or vulnerabilities are added upstream.
# How we plan to use Clair

We want to have Clair running on cloud.gov and running continuous scans of the images in our trusted registry. When a scan reveals a vulnerability, it should be reported to the Federalist engineering team and to the 18F devops team, ideally via email.

We can use Clair in the short-term to do local scanning for the purposes of achieving a short-term ATO.

**Comment by jmhooper** [comment]
I've been using Clair to scan the images we post to our private registry (see #543).

To get this working you need to:

- Set some shell variables
- Start up Clair with Docker and wait for vulnerability updates
- Use Clair CLI tool to scan images

The Clair CLI tool will require you to have `go` installed and `$GOPATH` set in your shell.

### Set some shell variables

Clair's CLI tool copies the image to a `tmp` directory where Clair picks it up. In order for this to work, you need to change the value of the `TMPDIR` variable to `/tmp`

```shell
export TMPDIR=/tmp
```

Additionally, if you do not have your `GOPATH` set, you'll need to set that.

### Start up Clair with Docker and wait for vulnerability updates

ref: https://github.com/coreos/clair

To start Clair, I have been using Docker Compose. Clair provides an [example configuration](https://github.com/coreos/clair/blob/master/docker-compose.yml). I've been using a slightly modified version:

```yaml
version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair
    environment:
      - "TMPDIR=/tmp"
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]
```

Clair will look for a config file in `./clair_config/config`. I've been using [Clair's example config](https://github.com/coreos/clair/blob/master/config.example.yaml).

```shell
curl -L https://raw.githubusercontent.com/coreos/clair/v1.2.2/config.example.yaml -o ./config/config.yaml
```

Once those parts are in place. You can start Clair with Docker Compose and watch the logs for it to update it's vulnerabilities. This may take a few minutes.

```shell
docker-compose up
```

### Use Clair CLI tool to scan an images

ref: https://github.com/coreos/clair/tree/master/contrib/analyze-local-images

First install the CLI tool:

```shell
go get -u github.com/coreos/clair/contrib/analyze-local-images
```

Then use it to scan your image:

```shell
analyze-local-images <IMAGE ID>
```

It can take a while, but it should get back to you with a report about whatever vulnerabilities it finds.
