### ISSUE TITLE
Setup trusted registry for docker images

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#543]
If we want to deploy apps that run in Docker containers, we need to deploy a Docker registry to cloud.gov and pull the images from that registry when we deploy.

Note that as part of this work, we'll need to configure the registry to communicate with Clair so that our images are scanned for vulnerabilities.

**Comment by jmhooper** [comment]
We currently have a private registry running on staging. I've tested starting apps from images hosted on this registry and it has worked.

The image uses an [S3 storage backend](https://docs.docker.com/registry/storage-drivers/s3/)

One tricky thing that we ran into here was authentication with the registry. We wanted to be able to pull images without auth, but require auth to push them. To use Docker's built-in auth to achieve this, we would need to build a [token authentication system](https://docs.docker.com/registry/spec/auth/token/) which adds a lot of overhead.

What we ended up doing, was pushing the registry with "read-only mode" enabled. Now we can start a local registry with the same storage backend, but with read-only mode disabled. This allows us to push images to the local registry, and have them appear on our remote private registry hosted in cloud.gov.

You cannot push directly to private registry, so unauthorized third parties cannot host their images there.

Here's what the docker-compose config for my local registry looks like:

```yaml
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE: s3
    REGISTRY_STORAGE_S3_ACCESSKEY: <S3 Access Key>
    REGISTRY_STORAGE_S3_BUCKET: <S3 Bucker Name>
    REGISTRY_STORAGE_S3_REGION: us-gov-west-1
    REGISTRY_STORAGE_S3_SECRETKEY: <S3 Secret Key>
```

If I set the S3 keys and bucket to be the same as the private registry on cloud.gov, I can push an image like this:

```
docker push localhost:5000/my-docker-image
```

And then start an app with that image like this:

```
cf push my-app-name -o "federalist-registry-staging.fr.cloud.gov/my-docker-image
```
